### ISSUE TITLE
Support `disabled_rules` key in .editorconfig syntax

### ISSUE THREAD

**Issue by nbadal** [nbadal/ktlint-intellij-plugin#97] opened 2021-06-24 00:15 UTC
It would be nice if this wasn't marked as an error, had autocomplete, etc

**Comment by paul-dingemans** [comment] 2023-10-25 19:56
Disabling rules shouldn't be too easy (e.g. being an option in the quick fix menu) as this violates the anti bikeshedding paradigm of ktlint. Of course, it is still possible to disable rules manually by editing the `.editorconfig`.

**Comment by paul-dingemans** [comment] 2023-10-28 19:35
Now I reread the issue, I think it is more related to [this comment](https://github.com/nbadal/ktlint-intellij-plugin/issues/300#issuecomment-1783823753) in #300.

**Comment by paul-dingemans** [comment] 2024-03-19 15:46
> Now I reread the issue, I think it is more related to [this comment](https://github.com/nbadal/ktlint-intellij-plugin/issues/300#issuecomment-1783823753) in #300.

Most likely duplicate of above

**Closed by paul-dingemans** 2024-03-19 15:46 UTC
Labels: enhancement
