### ISSUE TITLE
External ruleset JARS not annotating issues.

### ISSUE THREAD

**Issue by ConorGarry** [nbadal/ktlint-intellij-plugin#45] opened 2021-02-12 06:55 UTC
I have created a jar file with my custom ruleset, it works fine when I run ktlint from command line, my custom rules are picked up. When I set this jar in `External ruleset JARS --ruleset` in the plugin, it doesn't pick up on my issues in the IDE (Android Studio 4.1.2).
In fact, it doesn't pick up on _any_ rules, seems that it doesn't use the pre-packaged ruleset either.

My expectation would be that I could add my custom ruleset jar in addition to current rules, but when I set it, IDE doesn't annotate any rules.

**Comment by nbadal** [comment] 2021-02-13 22:29
@ConorGarry thanks for the heads up! I'll take a look at this asap

**Comment by nbadal** [comment] 2021-02-16 16:11
Fixed, will be included in an update this week 😁

**Closed by nbadal** 2021-02-16 16:11 UTC
Labels: bug

**Comment by coyarzun89** [comment] 2021-04-30 21:43
Hi there, I have the same problem. If I run klint from command line, the report shows my custom rules, but they are never displayed in the IDE (Android Studio 4.1.3). I'm using the latest version (0.7.5).
Does this fix worked for you @ConorGarry?
<img width="1648" alt="Screen Shot 2021-04-30 at 17 42 39" src="https://user-images.githubusercontent.com/1242575/116757117-77eec200-a9db-11eb-8fff-3b23550a61e5.png">

<img width="1109" alt="Screen Shot 2021-04-30 at 17 40 44" src="https://user-images.githubusercontent.com/1242575/116757010-33632680-a9db-11eb-8ab1-b2b0653b8f1c.png">

**Comment by nbadal** [comment] 2021-05-01 16:12
@coyarzun89 Just re-checked my test rules (which are admittedly simple), and they appear as annotations for me. I wonder if it's something specific about the kind of rule you're applying. Would you be willing to share an example rule that isn't appearing?

**Comment by coyarzun89** [comment] 2021-05-01 18:05
Yep, this is the rule that I was testing. It's to enforce the use of the prefix `Data` on models inside a specific package. <img width="1648" alt="Screen Shot 2021-05-01 at 14 03 03" src="https://user-images.githubusercontent.com/1242575/116791077-f56f0c80-aa85-11eb-80b6-30f8ddc4ba1f.png">

I was testing it in a sample project with this file:
<img width="1648" alt="Screen Shot 2021-05-01 at 14 00 13" src="https://user-images.githubusercontent.com/1242575/116791055-d07a9980-aa85-11eb-8d3c-46a530f0c71f.png">

And in the report is included, but not in the IDE, so I'm not sure where is the problem.
<img width="1648" alt="Screen Shot 2021-04-30 at 17 42 39" src="https://user-images.githubusercontent.com/1242575/116757117-77eec200-a9db-11eb-8fff-3b23550a61e5.png">

**Comment by nbadal** [comment] 2021-05-01 18:23
Thanks! I'll take a look using this as a test case 😄

**Comment by nbadal** [comment] 2021-05-01 19:31
@coyarzun89 Try compiling your rule using `ElementType.PACKAGE_DIRECTIVE` or `KtNodeTypes.PACKAGE_DIRECTIVE` when comparing `node.elementType`. I can't find any supporting documentation to indicate which is the "correct" approach, but I'll ask around.

I think one class somewhere in there has a bug in its `equals()` method, and the resolved object is a separate instance because the IDE has its own separate Kotlin compiler. I'll do some digging to find out what's causing this regardless

**Comment by nbadal** [comment] 2021-05-01 19:43
I was able to reproduce the issue, and the debugger results are interesting 🤔 

![Screen Shot 2021-05-01 at 12 42 15 PM](https://user-images.githubusercontent.com/394812/116793270-ab345e00-aa7a-11eb-9cbd-5c25589c4f95.png)

**Comment by nbadal** [comment] 2021-05-01 20:00
Okay, I've found the cause! `org.jetbrains.kotlin.psi.*` classes are shadowed in my plugin due to collisions with the IDE's built-in kotlin compiler. 

I created a new issue to track this: #76

**Comment by coyarzun89** [comment] 2021-05-02 16:45
Thank you so much for the debugging! I'll give it a try to use `ElementType.PACKAGE_DIRECTIVE`

**Comment by nbadal** [comment] 2021-05-02 21:57
If that doesn't work, the fix will be out in 0.7.6 soon 😀
