### ISSUE TITLE
Add support for multiple/runtime-specific versions of ktlint

### ISSUE THREAD

**Issue by IvanPizhenko** [nbadal/ktlint-intellij-plugin#35] opened 2021-01-23 22:07 UTC
I have a code like this:
```  
  val someVar = when (ctx.path()) {
      "/some/path/here" -> {
        println("hello")
      }
      else -> ctx.attribute<AttributeClassName>(Attributes.ATTRIBUTE_IDENTIFIER)
        ?: throw MyException("some error message")
    }
    println(someVar.toString())
```
IDE with installed ktlint plugin is happy with this code, i.e. doesn't put red marks.
But when I run my Gradle build, ktlint check compains at the same code:
 ```
SourceFileName.kt:123:13: Missing newline after "->"
```
I'm expecting that should plugin also detect this inconsistency, but actually it is not.

**Comment by IvanPizhenko** [comment] 2021-01-23 22:25
Here is my editorconfig:
 [editorconfig.txt](https://github.com/nbadal/ktlint-intellij-plugin/files/5861204/editorconfig.txt)

**Comment by IvanPizhenko** [comment] 2021-01-23 22:34
Here are some more IntelliJ configs (uploading as txt because github doesn't want to accept xml attachment):
[codeStyleConfig.xml.txt](https://github.com/nbadal/ktlint-intellij-plugin/files/5861218/codeStyleConfig.xml.txt)
[Project.xml.txt](https://github.com/nbadal/ktlint-intellij-plugin/files/5861220/Project.xml.txt)
[ktlint.xml.txt](https://github.com/nbadal/ktlint-intellij-plugin/files/5861224/ktlint.xml.txt)

**Comment by nbadal** [comment] 2021-01-23 22:47
Thanks for flagging this and for the sample files! I'll take a look today 😄

**Comment by nbadal** [comment] 2021-01-23 23:29
@IvanPizhenko is it possible this is caused by #28 ? The workaround / way to test this would be to explicitly set the folder for your `.editorconfig` in the plugin settings.

I wasn't able to reproduce that ktlint error with a short example, but that message comes from the `indent` rule, so maybe it only gets triggered under more complex circumstances 🤔

**Comment by IvanPizhenko** [comment] 2021-01-23 23:36
@nbadal Yes, I've faced #28, but I've added explicit path to the editorconfig, you can see `<editorConfigPath>$PROJECT_DIR$</editorConfigPath>` in the attached ktlint.xml. So this one is already mitigated. I have the plugin generally working, but in this particular situation it doesn't work correctly.

**Comment by IvanPizhenko** [comment] 2021-01-23 23:38
I will try to make it reproduced in a small sample project.

**Comment by IvanPizhenko** [comment] 2021-01-24 01:05
Here is sample project https://github.com/IvanPizhenko/kotlin-sample-project

**Comment by IvanPizhenko** [comment] 2021-01-24 01:09
Look here https://github.com/IvanPizhenko/kotlin-sample-project/blob/bb95c355aa5e78af4b2744b0d70fb080bc5c2282/module1/src/main/kotlin/org/example/Controller.kt#L15

**Comment by nbadal** [comment] 2021-01-24 02:23
Awesome, thank you! I'll make sure to distill this down into a test case as well once I've got that set up 😁 

Looking into it now, then I'll publish a fix in 0.7.1 hopefully 🤞

**Comment by nbadal** [comment] 2021-01-24 04:09
I think this may be due to the gradle ktlint plugin using ktlint 0.39.0, and my plugin using 0.40.0 – I'll have to verify this tomorrow morning, but using `ktlint` v0.40.0 on the command line directly also doesn't show the error that the gradle plugin does.

This might be fixed by https://github.com/pinterest/ktlint/issues/901 ? Seems like a relevant entry in the 0.40.0 changelog
I'll get my hands on 0.39.0 in the morning to double check though!

**Comment by IvanPizhenko** [comment] 2021-01-24 08:54
Tried setting ktlint version to 0.40.0 in the gradle - it worked. 
But what we really need is to be able to set the same version of ktlint in the both gradle and IntelliJ plugin.
Can you please add such possibility? It could be this way: a checkbox and edit field in the plugin configuration page, like this
![configuration](https://user-images.githubusercontent.com/11859904/105625479-5b6a4900-5e32-11eb-9a5a-250eb0c06823.jpg)
if checkbox is checked, specific version is used, otherwise - whatever default version you apply (I assume it checks for the latest version).

**Comment by nbadal** [comment] 2021-01-24 17:31
That would be a nice feature – albeit a bit trickier to implement within the confines of the IDE plugin, but it might be possible!

I'll add it to the roadmap 😄

**Comment by alexfacciorusso** [comment] 2021-07-12 13:49
@nbadal If you wouldn't mind, I could try finding some spare time to develop this feature and contribute to the plugin? I don't want to step on anyone else's toes if someone is already on it!

**Comment by nbadal** [comment] 2021-07-12 15:07
@alexfacciorusso absolutely, take a stab at it!

**Comment by erikhuizinga** [comment] 2023-03-10 11:35
I'm also interested in this feature. Until then, this plugin is probably not very UX friendly for me.

I specifically use https://github.com/JLLeitschuh/ktlint-gradle to simply run ktlint as Gradle tasks (e.g. `ktlintCheck`, `ktlintFormat`). If this IDEA plugin would allow setting the ktlint version or executable location, and if the ktlint Gradle plugin declares where its executable is located, then I could bridge the gap.

Wishful thinking: have your plugin detect the Gradle plugin and use its executable, even if it later updates to a newer version.

**Comment by IvanPizhenko** [comment] 2023-03-10 19:52
Any chance to have it in the nearest next version?

**Comment by nbadal** [comment] 2023-03-14 22:03
I haven't heard any progress from @alexfacciorusso - I can start to take a look at this again

**Comment by takanuva15** [comment] 2023-04-02 18:25
> I specifically use https://github.com/JLLeitschuh/ktlint-gradle to simply run ktlint as Gradle tasks (e.g. `ktlintCheck`, `ktlintFormat`). If this IDEA plugin would allow setting the ktlint version or executable location, and if the ktlint Gradle plugin declares where its executable is located, then I could bridge the gap.

Lol I read this and got a smile since I'm in the same boat. I maintain a different IntelliJ plugin that uses Kotlin and I use the same `org.jlleitschuh.gradle.ktlint` plugin for linting my kotlin files. By default, it's using ktlint v47 but this plugin uses ktlint v48 so they're out-of-sync. Would be nice to be able to specify the ktlint version as well.

@nbadal Could you point me to the class(es) I should look at which determine the version of ktlint that's downloaded? I've done plugin and UI work with IntelliJ's platform so I could try poking around to see if I can make a custom version box of some kind work.

**Comment by paul-dingemans** [comment] 2023-11-06 20:15
I have had a look at how this is done in `ktlint-gradle` plugin. My Gradle knowledge is too limited to get this working.

**Comment by paul-dingemans** [comment] 2024-03-19 14:07
Next version of plugin supports ktlint versions 0.50.0, 1.0.1, 1.1.1 and 1.2.1.

**Comment by paul-dingemans** [comment] 2024-04-07 14:20
This feature will be postponed. Current solution has unwanted side effect that size of plugin increases with 64MB per version of ktlint rules included. See #498.

**Closed** 2024-04-10 11:10 UTC
Labels: enhancement
