### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by krzema12** [nbadal/ktlint-intellij-plugin#532] opened 2024-06-10 06:06 UTC
<img width="675" alt="Screenshot 2024-06-10 at 08 06 00" src="https://github.com/nbadal/ktlint-intellij-plugin/assets/3110813/00590413-e00f-4907-8be2-a688d3459733">

They start taking an enormous amount of space on my little 13" screen.
I believe the old ones should be removed in favor of the new, updated one.

**Comment by paul-dingemans** [comment] 2024-06-10 06:16
Yeah, this is really inconvenient and not intended. I have not found a reproduction path, and it only happened once on my machine. So if you have any idea how to reproduce, please let me know.On 10 Jun 2024 08:07, Piotr Krzemiński ***@***.***> wrote:
Screenshot.2024-06-10.at.08.06.00.png (view on web)
They start taking an enormous amount of space on my little 13" screen.
I believe the old ones should be removed in favor of the new, updated one.

**Comment by paul-dingemans** [comment] 2024-06-11 08:53
What is the version of the plugin you are using? And what is the content of file `.idea/ktlint-plugin.xml` in the project that reproduces the problem?

**Comment by paul-dingemans** [comment] 2024-06-11 09:13
Duplicate of #522

**Closed by paul-dingemans** 2024-06-11 09:13 UTC
